# version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./www:/var/www/html
    depends_on:
      # - wordpress
      - php-fpm
      - db
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:6-fpm-alpine
    volumes:
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # - ./php/extensions/xx.so:/usr/local/lib/php/extensions/no-debug-non-zts-20220829/xx.so:ro
      - ./www:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}

  php-fpm:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # - ./php/extensions/xx.so:/usr/local/lib/php/extensions/no-debug-non-zts-20230831/xx.so:ro
      - ./www:/var/www/html:rw
    restart: always

  db:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - "./db:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    cap_add:
      - SYS_NICE
